package org.Cricket;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import io.github.bonigarcia.wdm.WebDriverManager;
public class Jadeja {
	public static void main(String[] args) throws InterruptedException {
	WebDriverManager.chromedriver().setup();
	WebDriver driver=new ChromeDriver();
	driver.get("http://www.adactin.com/HotelApp/");
	driver.manage().window().maximize();
	WebElement name=driver.findElement(By.name("username"));
	name.sendKeys("ArvinthanJoshna");
	WebElement pass=driver.findElement(By.name("password"));
	pass.sendKeys("ArvinthanJoshna1326");
	WebElement login=driver.findElement(By.name("login"));
	login.click();
	Thread.sleep(2000);
	WebElement location=driver.findElement(By.name("location"));
	Select sc=new Select(location);
	sc.selectByValue("Melbourne");
	WebElement hotel=driver.findElement(By.name("hotels"));
	Select s=new Select(hotel);
	s.selectByValue("Hotel Sunshine");
	WebElement room=driver.findElement(By.name("room_type"));
	Select sr=new Select(room);
	sr.selectByValue("Super Deluxe");
	WebElement roomno=driver.findElement(By.name("room_nos"));
	Select srn=new Select(roomno);
	srn.selectByVisibleText("1 - One");
	WebElement adult=driver.findElement(By.name("adult_room"));
	Select sa=new Select(adult);
	sa.selectByVisibleText("2 - Two");
	WebElement child=driver.findElement(By.name("child_room"));
	Select sc1=new Select(child);
	sc1.selectByVisibleText("0 - None");
	WebElement submit=driver.findElement(By.name("Submit"));
	submit.click();
	Thread.sleep(2000);
	WebElement click=driver.findElement(By.name("radiobutton_0"));
	click.click();
	WebElement cont=driver.findElement(By.name("continue"));
	cont.click();
	Thread.sleep(2000);
	WebElement fname=driver.findElement(By.name("first_name"));
	fname.sendKeys("Arvinthan");
	WebElement lname=driver.findElement(By.name("last_name"));
	lname.sendKeys("Arvinthan");
	WebElement add=driver.findElement(By.name("address"));
	add.sendKeys("Chennai");
	WebElement card=driver.findElement(By.name("cc_num"));
	card.sendKeys("1234098756102938");
	WebElement cardtype=driver.findElement(By.name("cc_type"));
	Select scd=new Select(cardtype);
	scd.selectByValue("VISA");
	WebElement month=driver.findElement(By.name("cc_exp_month"));
	Select sm=new Select(month);
	sm.selectByVisibleText("January");
	WebElement year=driver.findElement(By.name("cc_exp_year"));
	Select sy=new Select(year);
	sy.selectByValue("2030");
	WebElement cvv=driver.findElement(By.name("cc_cvv"));
	cvv.sendKeys("261");
	WebElement book=driver.findElement(By.name("book_now"));
	book.click();
	Thread.sleep(8000);
	WebElement order=driver.findElement(By.name("order_no"));
	String od=order.getAttribute("Z707Z0FZ1B");
	System.out.println(od);
	}
}
