package org.Cricket;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import io.github.bonigarcia.wdm.WebDriverManager;
public class SmitiMandhana {
	public static void main(String[] args) throws AWTException, InterruptedException {
	WebDriverManager.chromedriver().setup();
	WebDriver driver=new ChromeDriver();
	driver.get("http://www.greenstechnologys.com/");
	JavascriptExecutor js=(JavascriptExecutor)driver;
	WebElement down=driver.findElement(By.xpath("(//span[@class='red_text'])[14]"));
	js.executeScript("arguments[0].scrollIntoView(true)", down);
	String attribute=down.getText();
	System.out.println(attribute);
	WebElement up=driver.findElement(By.xpath("//h1[text()='No 1 Software Training Institutes in Chennai with Placements']"));
	js.executeScript("arguments[0].scrollIntoView(false)", up);
	String print=up.getText();
	System.out.println(print);
	WebElement certi=driver.findElement(By.xpath("//a[text()='Certifications']"));
	js.executeScript("arguments[0].click()", certi);
	Robot r=new Robot();
	WebElement sele=driver.findElement(By.xpath("(//a[text()='Course Content'])[29]"));
	js.executeScript("arguments[0].scrollIntoView(true)", sele);
    js.executeScript("arguments[0].click()", sele);
    WebElement test=driver.findElement(By.xpath("//b[text()='Learn Selenium Training In Chennai From The Experts!']"));
    String msg=test.getText();
    System.out.println(msg);
    WebElement top=driver.findElement(By.xpath("//h2[text()='Selenium Training in Chennai']"));
    String msg1=top.getText();
    System.out.println(msg1);
    Actions mov=new Actions(driver);
    WebElement mouse=driver.findElement(By.xpath("//a[text()='COURSES']"));
    mov.moveToElement(mouse).perform();
    WebElement mouse1=driver.findElement(By.xpath("//a[text()='Java Training ']"));
    mov.moveToElement(mouse1).perform();
    WebElement core=driver.findElement(By.xpath("//a[text()='Core Java Training']"));
    core.click();
    WebElement anitha=driver.findElement(By.xpath("//h2[text()='Java training Reviews from Anitha']"));
    String msg2=anitha.getText();
    System.out.println(msg2);
    WebElement career=driver.findElement(By.xpath("//a[text()='CAREERS']"));
    career.click();
    WebElement mail=driver.findElement(By.xpath("(//a[text()='contact@greenstechnologys.com'])[14]"));
    String msg3=mail.getText();
    System.out.println(msg3);
    driver.navigate().back();
    Thread.sleep(8000);
    WebElement test1=driver.findElement(By.xpath("//a[text()='TESTIMONIALS']"));
    test1.click();
    WebElement no=driver.findElement(By.xpath("//a[text()='+91 8939 915 577 ']"));
    String msg4=no.getText();
    System.out.println(msg4);
    WebElement thank=driver.findElement(By.xpath("(//div[@class='testimonial-section'])[17]"));
    String msg5=thank.getText();
    System.out.println(msg5);
    driver.navigate().back();
    Thread.sleep(8000);
    WebElement contact=driver.findElement(By.xpath("//a[text()='CONTACT US']"));
    contact.click();
    WebElement our=driver.findElement(By.xpath("//h3[text()='Our Main Branches In Chennai ']"));
    String msg6=our.getText();
    System.out.println(msg6);
    WebElement copy=driver.findElement(By.xpath("//p[text()='Copyright © 2023 Greens Technology. All rights reserved.']"));
    String msg7=copy.getText();
    System.out.println(msg7);
	}
}
